export { default as Companies } from './Companies/Companies';
export { default as Company } from './Companies/Company';
export { default as Dashboard } from './Dashboard/Dashboard';
export { default as Home } from './Home/Home';
export { default as Property } from './Property/Property';
export { default as RealEstates } from './RealEstates/RealEstates';
export { default as SignIn } from './SignIn/SignIn';
export { default as SignUp } from './SignUp/SignUp';
export { default as Verify } from './Verify/Verify';
